style_edition = "2024"

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto" 

use_small_heuristics = "Default"

reorder_imports = true
reorder_modules = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate" 

wrap_comments = true
comment_width = 80

format_strings = true
format_macro_matchers = true
format_macro_bodies = true

empty_item_single_line = true
struct_lit_single_line = true 
fn_single_line = false 

where_single_line = false 
condense_wildcard_suffixes = false 
color = "Auto" 